### ISSUE TITLE
Hard coding channel limits portability

### ISSUE THREAD

**Issue by guyinacube** [migueesc123/YoutubeAnalytics#2]
Having to hard code the channel was unexpected. Have to change it to my channel and then rebuild the extension.  Makes this not very portable. I'm not sure if there is a way to alter the get data dialog to allow input of the channel value. 

I guess the same would be true for the appkey and secret. I don't know that you want all of that going through your API app.

**Comment by migueesc123** [comment]
thanks for the feedback, Adam!
For the past week or so I've been trying to put my head around the portability issue. Currently, the way that people can enter appkey and appsecret or other values like that is only through Visual Studio, but ChannelID could be a parameter inside a function.

It makes a lot of sense to add that parameter to the functions! but sadly, the parameter of that function would need to be optional which would cause some issues like the one that you see on the 2 functions that I have for the current connector. Since the parameters would be optional, they could be null and that's not good. Tables like the ChannelInfo or Videos would not even show in the navigation window as those would be functions with optional parameters.

From an EndUser perspective, I thought that the best way would be to hardcode that ChannelID in the *.mez file and then find a way to, through a web app, automate the process of creating a *.mez file. Like a simple website where people could enter the values of the connector logic and then just get the *.mez file without ever needing to install VS or the extensibility pack.

To a certain extent, I've been thinking about enabling the channelID as part of the functions that I've created (and optional as per the limitations of the #pqsdk) and then provide a companion pbit where people would enter their channelID, startdate and endddate and they'll just get everything (data model and report pages) nice and clean.

The last paragraph is the end goal. Not only a data connector but also a companion PBIT.

Let me know your thoughts!

**Comment by Hugoberry** [comment]
Re appkey and secret. I believe that YouTube analytics API has other methods for retrieving the data without the need for creating an App

**Comment by migueesc123** [comment]
Hey!

The main reason why I had to create the app, and the whole authentication, was for the metrics related to the revenue (ads+rev) that Google states can only be done through OAuth 2.0.

More info about that statement from Google here: https://developers.google.com/youtube/analytics/registering_an_application

An app that provides an API KEY would be sufficient if we were querying just the Youtube Data API (which only holds public data), but since we’re getting basically all the monetary and ad information then we forcefully need the OAuth 2.0

We could potentially even query that public data (views, likes and such) through some other means as well, like searches through some other endpoints of the Youtube API without actually using an app at all (since they don’t need any authentication), but you only get a few results per page so it has its limitations.

**Comment by migueesc123** [comment]
Hey @guyinacube ! I removed the necessity to input the ChannelID and now the ChannelID is automatically picked up by the authenticated user. All you need to enter now is simply the appkey and appsecret, then go through the OAuth and you're good to go! 

There were some huge improvements in the way that the calls were made and I basically removed any limitations that were based on how many videos you could get.

Let me know your thoughts about the new experience and if you're able to get all of your videos in Data Model. In paper, the code can get any number of videos per channel, but if you know someone that has over 500 videos and would like to put this connector to the test then send them my way :)
