### ISSUE TITLE
Expression.Error: Access to the resource is forbidden.

### ISSUE THREAD

**Issue by rfthomsen** [migueesc123/YoutubeAnalytics#22]
Hi

I'm having trouble getting this connector to work, and since I can see you're very responsive to other issues raised here, I thought I'd give it a try.

I've followed all the steps in your videos, i.e. created a Google API project with the YouTube APIs, added an OAuth2 client ID, downloaded the connector and modified it with the JSON file downloaded from the API console. However, when trying to connect in Power BI (both manually and using the template), I just get this:

> Expression.Error: Access to the resource is forbidden.

Is there anything I can do to troubleshoot this error? As it stands I'm really not sure where to begin.

Thanks in advance, and thanks for all your work on this great project!

**Comment by migueesc123** [comment]
hey!

That's a tough one to provide a general suggestion. I'm not extremely familiar with the API these days, and I never went super deep into the possible error messages since I started with a very narrow and focused approach. 
If everything is set up correctly, then the only reason why you're getting that error (probably a 403) is that the authenticated user is not the owner of the channel that you're trying to connect to. 
The way that this connector works is that once you log in, the connector will automatically find the channel that you selected and try to authenticate with your user against it as the owner of that channel. If you're not the owner, then you won't get a valid authentication. Could this be your case?

I highly recommend that you try signing in with another user / channel to see if the error is within the actual connect (or how it's set up) or if it has to do with the permissions that I mentioned before.

**Comment by rfthomsen** [comment]
Hey again

I should be an owner of the channel in question, but it's definitely worth going through the steps again with a different channel to see if I might have missed anything.

I also wonder if the error might be due to some changes in Google's API and/or authentication procedures since you made your walk-through. For example, when connecting with the custom connector in Power BI, there's an additional step in the OAuth process (after signing in) to select either the Google account or the YouTube channel:
![image](https://user-images.githubusercontent.com/49399725/55777140-52628900-5a9f-11e9-9978-2faafbfe8342.png)
Not sure if this has any impact on how the connector works.

Either way, I'll try a few different options to see if I can isolate the issue. Thanks for your response - it's really great that you're still responsive so long after making this connector!

**Comment by rfthomsen** [comment]
Well, seems like I resolved the issue by creating a new project in Google's API console, enabling YouTube APIs and setting up OAuth, and replacing the client key JSON file accordingly. I'm not really sure what I did differently from the first time, but since it works now, that's all that matters.

This connector is extremely helpful, and also provides some inspiration for me to start creating my own connectors when I'm a bit more confident with M. So thanks again for your work and your help!
