### ISSUE TITLE
OAuth Verification & Error 401: invalid_client

### ISSUE THREAD

**Issue by baxtak** [migueesc123/YoutubeAnalytics#44]
Hello, I managed to do most steps in your instructions, however I'm having some issues that I would love some help with.

1. In order to have the scopes: yt-analytics-monetary.readonly, yt-analytics.readonly & youtube.readonly, I need validate the App and for that, I need to provide Justification of why I need yt-analytics-monetary.readonly & youtube.readonly. 

Does something like "Access data for our business intelligence through Power Bi. We aim to get real-time information on monetisation and views statistics, and the following scopes are necessary" work?

2. To validate, I also need to submit a "Demo video: how will the scopes will be used? (A YouTube video link is required when selecting sensitive or restricted scopes)". What do you suggest for this?

3. I have the Connector showing on Power BI, but I receive a: "Error 401: invalid_client The OAuth client was not found." error. I'm fairly certain I've done all the correct steps you mentioned, but no luck yet :(

Thanks for any guidance possible!

**Comment by migueesc123** [comment]
Hey!
Unfortunately, I haven't been through that verification process myself as it does require quite a bit of documentation and even webpages that need to be publicly available, so I wouldn't be able to tell you exactly what needs to be in there. It's probably a better idea to post in the google forums to get direct help from the google team that reviews these sort of applications.

The 401: invalid client means that the OAuth consent screen hasn't been fully set up yet or that the webapp.json file for the connector doesn't contain your data for your web application. It's hard to tell, but it could be either one of those 2.

Hope this helps!

**Comment by baxtak** [comment]
Right, i see. Thanks for your response anyway. I think your tool is nearly complete, but it is impossible to actually carry out the steps required without the verification process, so I'm not sure if the tutorials are still entirely relevant. I'll see if i can find more information about the verification process and potentially link it back here for reference. Cheers

**Comment by ptyx507** [comment]
hey! thanks for the feedback. 

The team at Google / YouTube changed some processed during the last couple of years that have affecteed how things work for the web application. Sadly, we have no control over those hence why some things might not work so easily for new applications created as they're under the "new rules" directly from Microsoft.

However, what this repo provides is the code required for the custom connector to work. As long as you're able to find a web application that you can use (it doesn't have to be yours, it can be from somebody else which meets the Google Criteria), you will be able to use the WebApp.json file in the custom connector and run your queries.

The good thing is that the custom connector works, but it depends on you having a working webapp in order to make the calls to the API and that webapp is completely out of my control, so I can't provide any support for it.

Best!
