### ISSUE TITLE
MULTIPLE ACCOUNTS CONNECTION 

### ISSUE THREAD

**Issue by maxTerr** [migueesc123/YoutubeAnalytics#6]
Hey !

First of all, thanks for sharing your connector and template. 

Concerning your connector, would it be possible to add multiple accounts on a same report with all the datas you can currently getting from your connector (i.e revenue, watch time ...).
For example, if I want to connect 4 different youtube channels through a common dashboard with the total combined revenue and watchtime of the 4 channels, is it possible ? 

Thanks !
Max

**Comment by migueesc123** [comment]
Hey Max,

Thanks for the kind words. The initial and current scope of this custom connector only intended the use of this custom connector to the Content Owner and not for an account under a CMS or some sort of delegated access, hence why all the queries are created using the credentials of the Authenticated User. This was mainly implemented to make things easier for me and other YouTube channels who were using this report, as all we needed to do was to input our credentials and everything would be done for us, because we don't have other channels to look at. 

More about the reason for that [here](https://github.com/migueesc123/YoutubeAnalytics/issues/2) 

As a workaround, some people are creating multiple versions of this custom connector so they can connect to multiple channels using multiple authentications and then append the data over and over again, but this is something that I wouldn't recommend.

You could, however, use the 'GET Public Data' function to get some publicly available data. I highly encourage you to give that function a try.

Maybe in the future, once the custom connectors reach GA, I'll check this custom connector again, but for now I'm only working on fixing any bugs that might arise with the current state of this custom connector.

**Comment by maxTerr** [comment]
Hey,

Thanks for the quick reply,

I will try to investigate the "Get Public Data" function in order to see what type of data can be collected. 

Thanks again !
Max
