### ISSUE TITLE
Access forbidden

### ISSUE THREAD

**Issue by amey100** [migueesc123/YoutubeAnalytics#7]
![image](https://user-images.githubusercontent.com/36230461/36780693-b35acc62-1c99-11e8-9937-1b9b44dbc410.png)

**Comment by migueesc123** [comment]
Hey Amey100,

Are you getting this error after going through the Google Authentication window? or before that?

**Comment by migueesc123** [comment]
Also, are you getting this when you try using the template? or when you're using the connector by itself? I'd highly recommend that you make sure that your API is set up correctly as that error is often caused by either:
- The API not set up correctly
- Your query trying to access data that you don't have access to (like revenue data of another youtube channel)

This custom connector grabs the information of the primary channel of the authenticated user, so when you do the sign in operation, the connector automatically finds your primary channel and will only give you information related to that channel.

**Comment by amey100** [comment]
I am  getting this error after going through the Google Authentication window

**Comment by amey100** [comment]
will try the process again

**Comment by Alex-71** [comment]
Hello Miguel... is it possible to grab data from other channel different from Primary?.  Is there access to some ‘channel definition’ parameter that can be modified as user level?

Thanks!

**Comment by migueesc123** [comment]
Hey Alex,

Check out this [one](https://github.com/migueesc123/YoutubeAnalytics/issues/6) for a more comprehensive explanation about the subject.

You could also modify the project to your specific needs (specifically the line 145), so you can define the specific channelId that you want to get data from, but at this time I've paused all the development on this connector until the Custom Connectors reach GA where I'd need to validate a bunch of connectors (including this one) to make sure that they are ready to be published to the Power BI Service.

**Comment by cyril-evstratenko** [comment]
Hello, Miguel. 

Many thanks for your helpful connector and template. It's really great job.

But I have the same problem like Amey. I see Access warning. And in query editor, I see the problem with  only one query:
![image](https://user-images.githubusercontent.com/38804585/39392776-a7bec01c-4ac4-11e8-8f67-0a8f1fbc1f1e.png)

Could you say what may be wrong with that query or my account settings?
Thank you!

**Comment by migueesc123** [comment]
Hey komovski!

Just to confirm, the account that youre trying to query is a partnered channel, correct?

**Comment by cyril-evstratenko** [comment]
hmm... I'm not sure. This channel administered from the account, which I use to login in power bi. But I'm not the owner.

**Comment by migueesc123** [comment]
I'd probably recommend that you try changing that part of the code for DailyVideoStats to be:
`= YoutubeAnalytics.VideoStats(StartDate,EndDate, false)`

that last optional parameter asks you if you're a partner or not. The template that I created is intended for channels that are partnered since they'll have monetary information that others channels won't.

If you try querying monetary information from a channel that is not partnered then you'll get some errors.
Let me know if this helps out.

**Comment by cyril-evstratenko** [comment]
It helped! Thank you so much.
